module.exports = {
  USER_FETCHED: 'USER_FETCHED',
  NETSTAT_FETCHED: 'NETSTAT_FETCHED',
  IFSTAT_FETCHED: 'IFSTAT_FETCHED',
  NETWORK_COMMON_INFO_FETCHED: 'NETWORK_COMMON_INFO_FETCHED',
  PACKETS_INFO_FETCHED: 'PACKETS_INFO_FETCHED'
};